### ISSUE TITLE
D-Multi Status Update

### ISSUE THREAD

**Issue by dguis** [D-Multi-cTech/Roblox-Royale#1]
I have attempted to contact all of the D-Multi developer team, but at this point in time I still have received no response. I would be willing to help with the development of this project and would like the permission of cTechstudios to sponsor the project on our website. Despite our website currently being offline, we are currently working on an update with a variety of new game concepts and would be delighted to add Roblox-Royale to the mix. I have not begun working on the game, but I am in the process of learning the necessary details (of LUA and such) in order to be able to contribute to game development. Finally, I would just like to clarify how this game would make a profit. Would it be generated simply by in-game items? (I apologize for my unfamiliarity to Roblox). Furthermore, would D-Multi be required to contribute anything towards the costs of production and publication? If so, we would be perfectly willing to do so, we are simply trying to get all of the details as clear as possible. Thank you!
<a href="https://github.com/dguis"><h6>Officially Written by @dguis on behalf of D-Multi</h6><img src="https://dguis.github.io/RES/New%20Logos/DG50x50db.png"></a>

**Comment by dude2093350** [comment]
Thank you for your question, all rights, trademarks and copyrights will remain property of cTechstudios, LLC. And, as such you will NOT be required to pay any costs regarding developing or publishing the game. The profitability of the game may be through sponsorships, pay-to-play and/or in game items. Finally, do to the nature of Roblox, you may NOT acknowledge the game directly on your site, however you may reference the cTechstudios - Roblox-Royale page shown on the main page. Thank you for your support!

-Erik Christensen
CEO - cTechstudios, LLC.

**Comment by dguis** [comment]
Thanks for the clarification!
