### ISSUE TITLE
Oh Dear...

### ISSUE THREAD

**Issue by dude2093350** [D-Multi-cTech/Roblox-Royale#3]
It appears we have yet to be able to assemble a team. Does D-Multi wish to leave this project, if not we need you to be ready for development starting July 5th, 2019! Game should be RELEASED (Stable Beta) by June 2020! cTechstudios also has begin working on another Roblox project so we definitely need help to build this game.

**Comment by dguis** [comment]
I apologize to say that yes, D-Multi will have to leave this project. I have not received any reply from any of my employees or D-Multi managers, so we will be forced to leave this project as a company unless we receive any other details very soon. Unless cTechstudios is contacted with any other information in the near future, it is to be assumed that D-Multi has resigned from the project. That being said, I personally would still be willing to help in any way I can with the project. Thanks!
<a href="https://github.com/dguis"><h6>Officially Written by dguis from D-Multi</h6><img src="https://dguis.github.io/RES/New%20Logos/DG50x50db.png"></a>

**Comment by dguis** [comment]
An automated repository transfer has been scheduled for 6/25/2019. If no information is heard from other D-Multi employees by then, the repo will automatically be transferred from the D-Multi-cTech organization to the cTech organization. Thanks!
<a href="https://github.com/D-Multi"><h6>Officially Written on behalf of D-Multi</h6><img src="https://dguis.github.io/RES/New%20Logos/DM50x50db.png"></a>

**Comment by dude2093350** [comment]
Thank you, we are arranging a new contract with another, private company. Unfortunately do to the nature of this project we can not have you contribute as an individual. We thank you for your support and wish you well as this concludes the cTechstudios-D-Multi development partnership.

With regards,
dude2093350 CEO
cTechstudios, LLC.

awesomekid10123 COO
cTechstudios, LLC.

Richard Gard Representative
Reverb Communications, Inc.

**Comment by dude2093350** [comment]
*Richard Gaurde
